### ISSUE TITLE
[BUG]: Internal server error on simple example

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3275]
### Describe the bug

The attached link yields "internal server error"

### Steps to reproduce

click the link

### Expected behavior

Should Just Work™

### Reproduction link

https://godbolt.org/z/68dfa6Mxv

### Screenshots

Not applicable

**Comment by mattgodbolt** [comment]
Seems to require having the `opt` view open.

**Comment by mattgodbolt** [comment]
Needs `-O2` and the `opt` view open

**Comment by mattgodbolt** [comment]
Seems like newer clangs make bad yaml docs:
```
error: Malformed inline YAML string ('i32 (...). {"domainThrown":true,"parsedLine":8,"snippet":"Type:            'i32 (..."}
```

**Comment by mattgodbolt** [comment]
Seems clang makes invalid yaml:
```yaml
--- !Missed
Pass:            inline
Name:            NoDefinition
DebugLoc:        { File: '/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../include/c++/11.0.0/bits/basic_ios.h', 
                   Line: 461, Column: 9 }
Function:        _ZNSt9basic_iosIcSt11char_traitsIcEEC2Ev
Args:
  - Callee:          _ZNSt8ios_baseC2Ev
  - String:          ' will not be inlined into '
  - Caller:          _ZNSt9basic_iosIcSt11char_traitsIcEEC2Ev
    DebugLoc:        { File: '/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/11.0.0/../../../../include/c++/11.0.0/bits/basic_ios.h', 
                       Line: 463, Column: 0 }
  - String:          ' because its definition is unavailable'
...
```

YAML parsers don't like the `!Missed` thing.
