### ISSUE TITLE
Weird clang format stdin behavior

### ISSUE THREAD

**Issue by jeremy-rifkin** [compiler-explorer/compiler-explorer#4985]
When I try to run clang-format on CE with the following configuration I get an error `<command-line>:1:179: error: unknown key 'AfterStruct'`
```
BasedOnStyle: Chromium
IndentWidth: 2
SpacesInAngles: false
SpaceAfterTemplateKeyword: false
PointerAlignment: Left
BreakBeforeBraces: Custom
BraceWrapping:
  AfterEnum: true
  AfterStruct: false
  SplitEmptyFunction: false
```
This config should be valid, tested locally with `cat s.txt | clang-format test.cpp`.

I am a couple major revisions behind locally so it may be that something was deprecated, but this BraceWrapping config is directly from the docs so I would guess it's still valid.
