### ISSUE TITLE
[BUG]: clang-tidy consistently times out on non-trivial snippets

### ISSUE THREAD

**Issue by alexolog** [compiler-explorer/compiler-explorer#5064]
### Describe the bug

clang-tidy consistently times out on non-trivial snippets

### Steps to reproduce

1. Go to https://godbolt.org/z/6c9nPa11j (just a quick example)
2. Trigger a compilation
3. Check the clang-tidy tab
4. See "Killed - processing time exceeded"

### Expected behavior

clang-tidy run should complete on moderately complex snippets.

### Reproduction link

https://godbolt.org/z/6c9nPa11j

### Screenshots

![image](https://github.com/compiler-explorer/compiler-explorer/assets/2112513/243dcadc-0a48-4e58-8e13-d9fdac94ed75)

**Comment by jeremy-rifkin** [comment]
Thanks for the report. Clang-tidy does seem to be taking a surprising amount of time to run.

I'm seeing this in the timing window:
![image](https://github.com/compiler-explorer/compiler-explorer/assets/51220084/8331ec20-dd8b-4421-9365-8c889a7e1a30)

I'm not sure if tool execution is lumped into the waiting time, if it is we should probably separate it.

**Comment by partouf** [comment]
Not sure we time tools, but would be good to do.

But... `--checks=*` minus some things is still a lot of things, and Clang-tidy also checks the system headers that you include, but there doesn't seem to be much to do about that.

You might be better off including only the checks that you want instead of subtracting from the entire set.

**Comment by alexolog** [comment]
Below is the set of checks we are using in our project, I'd like to be able to use it on Compiler Explorer.

```
---
Checks: '*
        ,-altera-*
        ,-android-*
        ,-fuchsia-*
        ,-llvm-*
        ,-llvmlibc-*
        ,-objc-*

        ,-modernize-use-trailing-return-type
        ,-bugprone-easily-swappable-parameters
        ,-readability-identifier-length
        ,-readability-redundant-access-specifiers
        ,-google-readability-todo
        ,-*-braces-around-statements
        ,-*-uppercase-literal-suffix
        ,-cert-dcl16-c
        ,-cert-dcl21-cpp

        ,-bugprone-exception-escape'
        # The above is disabled due to bugs in LLVM

CheckOptions:
  # Magic numbers, adjust as needed
  - key: readability-magic-numbers.IgnoredIntegerValues
    value: "0;1"
  - key: cppcoreguidelines-avoid-magic-numbers.IgnoredIntegerValues
    value: "0;1"
  - key: readability-magic-numbers.IgnoredFloatingPointValues
    value: "0.0;1.0;2.0;10.0;100.0;1000.0"
  - key: cppcoreguidelines-avoid-magic-numbers.IgnoredFloatingPointValues
    value: "0.0;1.0;2.0;10.0;100.0;1000.0"
  - key: readability-magic-numbers.IgnorePowersOf2IntegerValues
    value: true
  - key: cppcoreguidelines-avoid-magic-numbers.IgnorePowersOf2IntegerValues
    value: true

  - key: cppcoreguidelines-special-member-functions.AllowSoleDefaultDtor
    value: true
  - key: hicpp-special-member-functions.AllowSoleDefaultDtor
    value: true
  - key: cppcoreguidelines-special-member-functions.AllowMissingMoveFunctions
    value: true
  - key: hicpp-special-member-functions.AllowMissingMoveFunctions
    value: true
  - key: cppcoreguidelines-special-member-functions.AllowMissingMoveFunctionsWhenCopyIsDeleted
    value: true
  - key: hicpp-special-member-functions.AllowMissingMoveFunctionsWhenCopyIsDeleted
    value: true

  - key: google-readability-namespace-comments.ShortNamespaceLines
    value: "10"
  - key: llvm-namespace-comment.ShortNamespaceLines
    value: "10"

  - key: readability-implicit-bool-conversion.AllowIntegerConditions
    value: true
  - key: readability-implicit-bool-conversion.AllowPointerConditions
    value: true
  - key: readability-function-cognitive-complexity.Threshold
    value: "25"
  - key: readability-function-cognitive-complexity.DescribeBasicIncrements
    value: true
  - key: readability-function-cognitive-complexity.IgnoreMacros
    value: true

  - key: hicpp-signed-bitwise.IgnorePositiveIntegerLiterals
    value: true
  - key: misc-non-private-member-variables-in-classes.IgnoreClassesWithAllMemberVariablesBeingPublic
    value: true

  - key: concurrency-mt-unsafe.FunctionSet
    value: "posix"
...
```
